### ISSUE TITLE
Add docker-compose example

### ISSUE THREAD

**Issue by christophetd** [christophetd/duplicacy-autobackup#24]

**Comment by PMK** [comment]
Example of a docker-compose file with Webdav settings

```
version: '3'

services:
  backup:
    image: christophetd/duplicacy-autobackup
    restart: unless-stopped
    volumes:
      - "./duplicacy/pre-backup.sh:/scripts/pre-backup.sh"
      - "./duplicacy/post-backup.sh:/scripts/post-backup.sh"
      - "/home/user/server-data:/data"
    environment:
      - "BACKUP_NAME=backup-server"
      - "BACKUP_ENCRYPTION_KEY=myencryptionkey"
      - "BACKUP_SCHEDULE=20 4 * * *"
      - "BACKUP_LOCATION=webdav://user@example.com/webdav"
      - "DUPLICACY_WEBDAV_PASSWORD=mywebdavpassword"
      - "DUPLICACY_BACKUP_OPTIONS=-threads 1 -stats"
```
